name: Python application

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up uv
      uses: astral-sh/setup-uv@v7

    - name: Install dependencies
      run: uv sync --locked --group dev

    - name: Download and extract HiGHSstatic
      run: |
        wget https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.8.1%2B0/HiGHSstatic.v1.8.1.x86_64-linux-gnu-cxx11.tar.gz
        mkdir -p "${HOME}/.local"
        tar xfz HiGHSstatic.v1.8.1.x86_64-linux-gnu-cxx11.tar.gz -C "${HOME}/.local"
        echo "${HOME}/.local/bin" >> "${GITHUB_PATH}"

    - name: Test with pytest
      run: uv run --no-sync python -m pytest

  auto-merge-dependabot-non-major-updates:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions:
      pull-requests: write
      contents: write
      checks: read
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v3
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Merge Dependabot PRs
        if: ${{ steps.metadata.outputs.update-type != 'version-update:semver-major' }}
        run: gh pr merge --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
